package client;

import java.net.URISyntaxException;
import java.nio.ByteBuffer;
import java.nio.channels.AsynchronousSocketChannel;
import java.nio.channels.CompletionHandler;
import java.nio.charset.Charset;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Created by bebe on 2/18/15.
 */
public class CustomCompletionHandlerPipelineV1 extends ArrayBlockingQueue<AsynchronousSocketChannel> {

    private final int TMP_BUFFER_SIZE = 10000;
//    private final int TMP_BUFFER_SIZE = 18479;

    public CustomCompletionHandlerPipelineV1(int capacity, AsynchronousSocketChannel initChannel) {
        super(capacity);
        offer(initChannel);
    }

    private final CustomCompletionHandler<Integer, Attachment> WRITE_COMPLETION_STAGE = this::beginRead;

    public final CustomCompletionHandlerPipelineV1.CustomCompletionHandler<Void, Attachment>
            STAGE = (v, attachment) -> {
        try {
            attachment.getChannel().write(RequestBuilder.buildGetRequest(attachment.getUrl())
                    , attachment
                    , WRITE_COMPLETION_STAGE); // cache handler
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    };

    private final CustomCompletionHandler<Integer, Attachment<StringBuilder>>
            READ_COMPLETION_STAGE = (bytesRead, attachment) -> {
        attachment.addRead(bytesRead);// for tests
        String response = new String(attachment.getBuffer().array(), Charset.forName("UTF-8"));
        StringBuilder content = attachment.getContent();
        attachment.setBytesRead(attachment.getBytesRead() + bytesRead);

        if (attachment.getExpectedContentLength() == null) {
            if (attachment.getHeaders() != null) {
                response = attachment.getHeaders().toString() + response;
            }
            Integer contentLength = HttpSupport.parseContentLength(response);
            if (contentLength == null) {
                attachment.setHeaders(new StringBuilder(response));
            } else {
                attachment.setExpectedContentLength(contentLength);
                String headers = HttpSupport.parseHeaders(response);
                attachment.setHeaders(new StringBuilder(headers));
                attachment.setContent(new StringBuilder(HttpSupport.parseContent(response).trim()));
                attachment.setActualContentLength(attachment.getBytesRead() - headers.length());
            }
        } else {
            attachment.setActualContentLength(attachment.getActualContentLength() + bytesRead);
            content.append(response.trim());
        }
        if (attachment.getActualContentLength() != null && attachment.getExpectedContentLength() != null
                && attachment.getActualContentLength() >= attachment.getExpectedContentLength()) { // we just read remaining bytes
            offer(attachment.getChannel());
            continueRead(attachment);
        } else { // we read part of content but there are remaining in the channel
            beginRead(1, attachment);
        }
    };

    private void beginRead(int bytesWritten, Attachment<StringBuilder> attachment) {
        if (bytesWritten > 0) {
            attachment.setBuffer(ByteBuffer.allocate(TMP_BUFFER_SIZE));
            attachment.getChannel().read(attachment.getBuffer()
                    , attachment
                    , READ_COMPLETION_STAGE); // cache handler
        } else {
            STAGE.completed(null, attachment);
        }
    }

    private void continueRead(Attachment<StringBuilder> attachment) {
        String s = attachment.getContent().toString().trim();
        StringBuilder reads = new StringBuilder();
        attachment.getReads().forEach((integer) -> reads.append(",").append(integer));
        if (!s.equals(b)) {
            throw new AssertionError();
        }
        System.out.println(s.length() + " " + i.incrementAndGet() + " " + s.equals(b) + "  " + reads.toString() + " size " + size());
        //+ (s.equals(b) ? "" : new StringBuilder("\n" + s + "\n" + b)));
    }

    AtomicInteger i = new AtomicInteger();

    /**
     * Extended to support lambda and default method and provide
     * default functionality
     *
     * @param <V>
     * @param <A>
     */
    interface CustomCompletionHandler<V, A> extends CompletionHandler<V, A> {

        @Override
        default void failed(Throwable exc, A attachment) {
            System.out.println(exc);
        }
    }

    String b =
            "vCONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1" +
                    "CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1CONTENT1"
                    + "END";

}
